-- ============================================================
-- SQL BUSINESS INTELLIGENCE PROJECT
-- File: 02_customer_analysis.sql
-- Database: sql_business_intelligence
-- Platform: PostgreSQL
-- Module: Customer Intelligence
-- ============================================================

/*
PURPOSE
-------
This script provides a comprehensive customer analysis for the
SQL Business Intelligence project.

BUSINESS QUESTIONS
------------------
01. Who are the highest-value customers?
02. Which customers generate the most revenue?
03. How many customers make repeat purchases?
04. What is the repeat customer rate?
05. How concentrated is revenue across customers?
06. Do the top customers generate approximately 80% of revenue?
07. How many customers are responsible for 80% of revenue?
08. Which customer segments perform best?
09. Which countries contain the highest-value customers?
10. What is the average customer purchase frequency?
11. Which customers have become inactive?
12. Which customers are at risk of becoming inactive?
13. Which customers have the highest average order value?
14. How does new vs repeat customer revenue compare?
15. Which customers generate the most gross profit?
16. What percentage of customers are responsible for the top 20% of revenue?
17. How can customers be grouped into value tiers?
18. What customer-level dataset can be used for BI reporting?

NOTES
-----
Only Completed orders are treated as realized sales unless stated
otherwise.

The dataset covers 2022-2025. Therefore, inactivity calculations use
2025-12-31 as the analytical reference date rather than CURRENT_DATE.
*/


-- ============================================================
-- 01. CUSTOMER LIFETIME VALUE
-- ============================================================
-- Business value:
-- Measures total realized revenue generated by each customer and
-- identifies the most commercially valuable customer relationships.

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country,
    COUNT(DISTINCT o.order_id) AS completed_orders,
    SUM(oi.quantity) AS units_purchased,
    ROUND(SUM(oi.line_revenue), 2) AS lifetime_revenue,
    ROUND(
        SUM(oi.line_revenue)
        / NULLIF(COUNT(DISTINCT o.order_id), 0),
        2
    ) AS average_order_value
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN regions r
    ON c.region_id = r.region_id
WHERE o.order_status = 'Completed'
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country
ORDER BY lifetime_revenue DESC;


-- ============================================================
-- 02. TOP 20 CUSTOMERS BY REVENUE
-- ============================================================
-- Business value:
-- Identifies the customers contributing the largest absolute amount
-- of realized sales revenue.

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country,
    COUNT(DISTINCT o.order_id) AS orders,
    SUM(oi.quantity) AS units_purchased,
    ROUND(SUM(oi.line_revenue), 2) AS revenue
FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN regions r
    ON c.region_id = r.region_id
WHERE o.order_status = 'Completed'
GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country
ORDER BY revenue DESC
LIMIT 20;


-- ============================================================
-- 03. REPEAT CUSTOMERS
-- ============================================================
-- Business value:
-- Identifies customers who have completed more than one order,
-- providing a basic measure of customer retention.

WITH customer_orders AS (
    SELECT
        c.customer_id,
        COUNT(DISTINCT o.order_id) AS completed_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'Completed'
    GROUP BY c.customer_id
)
SELECT
    COUNT(*) AS repeat_customers
FROM customer_orders
WHERE completed_orders > 1;


-- ============================================================
-- 04. REPEAT CUSTOMER RATE
-- ============================================================
-- Business value:
-- Measures the percentage of purchasing customers who returned
-- and completed more than one order.

WITH customer_orders AS (
    SELECT
        c.customer_id,
        COUNT(DISTINCT o.order_id) AS completed_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'Completed'
    GROUP BY c.customer_id
)
SELECT
    COUNT(*) AS purchasing_customers,

    COUNT(*) FILTER (
        WHERE completed_orders = 1
    ) AS one_time_customers,

    COUNT(*) FILTER (
        WHERE completed_orders > 1
    ) AS repeat_customers,

    ROUND(
        100.0 *
        COUNT(*) FILTER (WHERE completed_orders > 1)
        / NULLIF(COUNT(*), 0),
        2
    ) AS repeat_customer_rate_pct
FROM customer_orders;


-- ============================================================
-- 05. CUSTOMER REVENUE CONCENTRATION
-- ============================================================
-- Business value:
-- Shows each customer's contribution to total company revenue
-- and highlights dependency on major customers.

WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        SUM(oi.line_revenue) AS revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment
)
SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    ROUND(revenue, 2) AS revenue,

    ROUND(
        100.0 * revenue
        / NULLIF(SUM(revenue) OVER (), 0),
        4
    ) AS revenue_share_pct

FROM customer_revenue
ORDER BY revenue DESC;


-- ============================================================
-- 06. PARETO 80/20 CUSTOMER ANALYSIS
-- ============================================================
-- Business value:
-- Calculates cumulative customer revenue contribution to determine
-- whether a relatively small customer group drives most sales.

WITH customer_revenue AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        SUM(oi.line_revenue) AS revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name
),

ranked_customers AS (
    SELECT
        customer_id,
        first_name,
        last_name,
        revenue,

        ROW_NUMBER() OVER (
            ORDER BY revenue DESC
        ) AS revenue_rank,

        SUM(revenue) OVER (
            ORDER BY revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS cumulative_revenue,

        SUM(revenue) OVER () AS total_revenue

    FROM customer_revenue
)

SELECT
    customer_id,
    first_name,
    last_name,
    revenue_rank,
    ROUND(revenue, 2) AS revenue,

    ROUND(
        100.0 * cumulative_revenue
        / NULLIF(total_revenue, 0),
        2
    ) AS cumulative_revenue_pct

FROM ranked_customers
ORDER BY revenue_rank;


-- ============================================================
-- 07. CUSTOMERS REQUIRED TO GENERATE 80% OF REVENUE
-- ============================================================
-- Business value:
-- Produces an executive KPI showing the minimum customer base
-- required to account for approximately 80% of company revenue.

WITH customer_revenue AS (
    SELECT
        c.customer_id,
        SUM(oi.line_revenue) AS revenue
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id
    WHERE o.order_status = 'Completed'
    GROUP BY c.customer_id
),

ranked AS (
    SELECT
        customer_id,
        revenue,
        ROW_NUMBER() OVER (
            ORDER BY revenue DESC
        ) AS customer_rank,
        SUM(revenue) OVER (
            ORDER BY revenue DESC
            ROWS BETWEEN UNBOUNDED PRECEDING
            AND CURRENT ROW
        ) AS cumulative_revenue,
        SUM(revenue) OVER () AS total_revenue
    FROM customer_revenue
),

threshold AS (
    SELECT
        *,
        100.0 * cumulative_revenue
        / NULLIF(total_revenue, 0) AS cumulative_pct
    FROM ranked
)

SELECT
    MIN(customer_rank) FILTER (
        WHERE cumulative_pct >= 80
    ) AS customers_required_for_80_pct,

    COUNT(*) AS total_purchasing_customers,

    ROUND(
        100.0 *
        MIN(customer_rank) FILTER (WHERE cumulative_pct >= 80)
        / NULLIF(COUNT(*), 0),
        2
    ) AS customer_base_pct

FROM threshold;


-- ============================================================
-- 08. CUSTOMER SEGMENT PERFORMANCE
-- ============================================================
-- Business value:
-- Compares customer segments by revenue, gross profit, customer count,
-- orders and average order value.

SELECT
    c.segment,

    COUNT(DISTINCT c.customer_id) AS customers,

    COUNT(DISTINCT o.order_id) AS orders,

    SUM(oi.quantity) AS units_sold,

    ROUND(
        SUM(oi.line_revenue),
        2
    ) AS revenue,

    ROUND(
        SUM(oi.line_revenue)
        - SUM(oi.quantity * oi.unit_cost),
        2
    ) AS gross_profit,

    ROUND(
        100.0 *
        (
            SUM(oi.line_revenue)
            - SUM(oi.quantity * oi.unit_cost)
        )
        / NULLIF(SUM(oi.line_revenue), 0),
        2
    ) AS gross_margin_pct,

    ROUND(
        SUM(oi.line_revenue)
        / NULLIF(COUNT(DISTINCT o.order_id), 0),
        2
    ) AS average_order_value

FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'Completed'

GROUP BY c.segment
ORDER BY revenue DESC;


-- ============================================================
-- 09. CUSTOMER PERFORMANCE BY COUNTRY
-- ============================================================
-- Business value:
-- Identifies geographic markets with the strongest customer value.

SELECT
    r.market,
    r.country,

    COUNT(DISTINCT c.customer_id) AS customers,

    COUNT(DISTINCT o.order_id) AS orders,

    ROUND(
        SUM(oi.line_revenue),
        2
    ) AS revenue,

    ROUND(
        SUM(oi.line_revenue)
        - SUM(oi.quantity * oi.unit_cost),
        2
    ) AS gross_profit,

    ROUND(
        SUM(oi.line_revenue)
        / NULLIF(COUNT(DISTINCT c.customer_id), 0),
        2
    ) AS revenue_per_customer,

    ROUND(
        SUM(oi.line_revenue)
        / NULLIF(COUNT(DISTINCT o.order_id), 0),
        2
    ) AS average_order_value

FROM customers c
JOIN regions r
    ON c.region_id = r.region_id
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id

WHERE o.order_status = 'Completed'

GROUP BY
    r.market,
    r.country

ORDER BY revenue DESC;


-- ============================================================
-- 10. CUSTOMER PURCHASE FREQUENCY
-- ============================================================
-- Business value:
-- Measures how frequently customers place completed orders and
-- distinguishes occasional buyers from highly engaged customers.

WITH customer_frequency AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        COUNT(DISTINCT o.order_id) AS completed_orders
    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    WHERE o.order_status = 'Completed'
    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment
)

SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    completed_orders,

    ROUND(
        AVG(completed_orders) OVER (),
        2
    ) AS avg_customer_order_frequency

FROM customer_frequency
ORDER BY completed_orders DESC;


-- ============================================================
-- 11. INACTIVE CUSTOMERS
-- ============================================================
-- Business value:
-- Identifies customers with no completed purchase during the
-- final 12 months of the analytical period.
--
-- Reference date = 2025-12-31 because the portfolio dataset
-- covers 2022-2025.
-- ============================================================

WITH customer_activity AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country,

        MAX(o.order_date) FILTER (
            WHERE o.order_status = 'Completed'
        ) AS last_completed_order

    FROM customers c

    LEFT JOIN orders o
        ON c.customer_id = o.customer_id

    LEFT JOIN regions r
        ON c.region_id = r.region_id

    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country
)

SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    country,
    last_completed_order,

    DATE '2025-12-31'
        - last_completed_order AS days_since_last_order

FROM customer_activity

WHERE last_completed_order IS NULL
   OR last_completed_order < DATE '2025-01-01'

ORDER BY last_completed_order NULLS FIRST;


-- ============================================================
-- 12. CUSTOMER RECENCY / CHURN-RISK PROXY
-- ============================================================
-- Business value:
-- Segments customers by time since their most recent completed order.
-- This creates a simple actionable retention-risk indicator.
-- ============================================================

WITH customer_activity AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,

        MAX(o.order_date) FILTER (
            WHERE o.order_status = 'Completed'
        ) AS last_completed_order

    FROM customers c

    LEFT JOIN orders o
        ON c.customer_id = o.customer_id

    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment
)

SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    last_completed_order,

    CASE
        WHEN last_completed_order IS NULL
            THEN 'Never Purchased'

        WHEN DATE '2025-12-31' - last_completed_order <= 90
            THEN 'Active'

        WHEN DATE '2025-12-31' - last_completed_order <= 180
            THEN 'Watch'

        WHEN DATE '2025-12-31' - last_completed_order <= 365
            THEN 'At Risk'

        ELSE 'Inactive'
    END AS customer_status,

    CASE
        WHEN last_completed_order IS NULL
            THEN NULL
        ELSE DATE '2025-12-31' - last_completed_order
    END AS days_since_last_order

FROM customer_activity
ORDER BY days_since_last_order NULLS LAST;


-- ============================================================
-- 13. TOP CUSTOMERS BY AVERAGE ORDER VALUE
-- ============================================================
-- Business value:
-- Identifies customers who typically place high-value orders,
-- even if they are not the highest-frequency buyers.
-- ============================================================

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country,

    COUNT(DISTINCT o.order_id) AS completed_orders,

    ROUND(
        SUM(oi.line_revenue),
        2
    ) AS revenue,

    ROUND(
        SUM(oi.line_revenue)
        / NULLIF(COUNT(DISTINCT o.order_id), 0),
        2
    ) AS average_order_value

FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN regions r
    ON c.region_id = r.region_id

WHERE o.order_status = 'Completed'

GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country

HAVING COUNT(DISTINCT o.order_id) >= 2

ORDER BY average_order_value DESC
LIMIT 20;


-- ============================================================
-- 14. NEW VS REPEAT CUSTOMER REVENUE
-- ============================================================
-- Business value:
-- Separates revenue generated from first purchases versus revenue
-- generated from returning customers.
-- ============================================================

WITH completed_orders AS (
    SELECT
        o.order_id,
        o.customer_id,
        o.order_date,

        SUM(oi.line_revenue) AS order_revenue,

        ROW_NUMBER() OVER (
            PARTITION BY o.customer_id
            ORDER BY o.order_date, o.order_id
        ) AS purchase_number

    FROM orders o
    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'Completed'

    GROUP BY
        o.order_id,
        o.customer_id,
        o.order_date
)

SELECT
    CASE
        WHEN purchase_number = 1
            THEN 'New Customer'
        ELSE 'Repeat Customer'
    END AS customer_type,

    COUNT(*) AS orders,

    ROUND(
        SUM(order_revenue),
        2
    ) AS revenue,

    ROUND(
        100.0 * SUM(order_revenue)
        / NULLIF(SUM(SUM(order_revenue)) OVER (), 0),
        2
    ) AS revenue_share_pct

FROM completed_orders

GROUP BY
    CASE
        WHEN purchase_number = 1
            THEN 'New Customer'
        ELSE 'Repeat Customer'
    END

ORDER BY revenue DESC;


-- ============================================================
-- 15. TOP CUSTOMERS BY GROSS PROFIT
-- ============================================================
-- Business value:
-- Revenue alone does not indicate profitability.
-- This analysis identifies customers creating the most gross profit.
-- ============================================================

SELECT
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country,

    COUNT(DISTINCT o.order_id) AS orders,

    ROUND(
        SUM(oi.line_revenue),
        2
    ) AS revenue,

    ROUND(
        SUM(oi.quantity * oi.unit_cost),
        2
    ) AS cost,

    ROUND(
        SUM(oi.line_revenue)
        - SUM(oi.quantity * oi.unit_cost),
        2
    ) AS gross_profit,

    ROUND(
        100.0 *
        (
            SUM(oi.line_revenue)
            - SUM(oi.quantity * oi.unit_cost)
        )
        / NULLIF(SUM(oi.line_revenue), 0),
        2
    ) AS gross_margin_pct

FROM customers c
JOIN orders o
    ON c.customer_id = o.customer_id
JOIN order_items oi
    ON o.order_id = oi.order_id
JOIN regions r
    ON c.region_id = r.region_id

WHERE o.order_status = 'Completed'

GROUP BY
    c.customer_id,
    c.first_name,
    c.last_name,
    c.segment,
    r.country

ORDER BY gross_profit DESC
LIMIT 20;


-- ============================================================
-- 16. TOP 20% OF CUSTOMERS VS REVENUE CONTRIBUTION
-- ============================================================
-- Business value:
-- Tests the classic 80/20 hypothesis from the opposite direction:
-- how much revenue is actually generated by the top 20% of customers?
-- ============================================================

WITH customer_revenue AS (
    SELECT
        c.customer_id,
        SUM(oi.line_revenue) AS revenue

    FROM customers c
    JOIN orders o
        ON c.customer_id = o.customer_id
    JOIN order_items oi
        ON o.order_id = oi.order_id

    WHERE o.order_status = 'Completed'

    GROUP BY c.customer_id
),

ranked AS (
    SELECT
        customer_id,
        revenue,

        ROW_NUMBER() OVER (
            ORDER BY revenue DESC
        ) AS revenue_rank,

        COUNT(*) OVER () AS total_customers,

        SUM(revenue) OVER () AS total_revenue

    FROM customer_revenue
),

top_customers AS (
    SELECT *
    FROM ranked

    WHERE revenue_rank <= CEIL(
        total_customers * 0.20
    )
)

SELECT
    COUNT(*) AS top_20_pct_customers,

    MAX(total_customers) AS total_customers,

    ROUND(
        SUM(revenue),
        2
    ) AS top_20_pct_revenue,

    ROUND(
        MAX(total_revenue),
        2
    ) AS total_revenue,

    ROUND(
        100.0 * SUM(revenue)
        / NULLIF(MAX(total_revenue), 0),
        2
    ) AS revenue_generated_pct

FROM top_customers;


-- ============================================================
-- 17. CUSTOMER VALUE TIERS
-- ============================================================
-- Business value:
-- Creates simple customer value segments that can be used by
-- management, marketing or account-management teams.
--
-- NTILE(4):
-- Tier 1 = highest-value 25%
-- Tier 4 = lowest-value 25%
-- ============================================================

WITH customer_metrics AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country,

        COUNT(DISTINCT o.order_id) AS orders,

        SUM(oi.line_revenue) AS revenue,

        SUM(oi.line_revenue)
        - SUM(oi.quantity * oi.unit_cost) AS gross_profit

    FROM customers c

    JOIN orders o
        ON c.customer_id = o.customer_id

    JOIN order_items oi
        ON o.order_id = oi.order_id

    JOIN regions r
        ON c.region_id = r.region_id

    WHERE o.order_status = 'Completed'

    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country
),

tiered AS (
    SELECT
        *,
        NTILE(4) OVER (
            ORDER BY revenue DESC
        ) AS value_quartile

    FROM customer_metrics
)

SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    country,
    orders,

    ROUND(revenue, 2) AS revenue,

    ROUND(gross_profit, 2) AS gross_profit,

    CASE
        WHEN value_quartile = 1
            THEN 'Tier 1 - High Value'

        WHEN value_quartile = 2
            THEN 'Tier 2 - Upper Mid Value'

        WHEN value_quartile = 3
            THEN 'Tier 3 - Lower Mid Value'

        ELSE 'Tier 4 - Low Value'
    END AS customer_value_tier

FROM tiered
ORDER BY revenue DESC;


-- ============================================================
-- 18. CUSTOMER BI SUMMARY DATASET
-- ============================================================
-- Business value:
-- Creates a reporting-ready customer-level analytical dataset.
-- This query can later be converted into a PostgreSQL VIEW and
-- connected directly to Power BI.
-- ============================================================

WITH customer_metrics AS (
    SELECT
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country,
        r.market,

        MIN(o.order_date) FILTER (
            WHERE o.order_status = 'Completed'
        ) AS first_order_date,

        MAX(o.order_date) FILTER (
            WHERE o.order_status = 'Completed'
        ) AS last_order_date,

        COUNT(DISTINCT o.order_id) FILTER (
            WHERE o.order_status = 'Completed'
        ) AS completed_orders,

        COALESCE(
            SUM(oi.quantity) FILTER (
                WHERE o.order_status = 'Completed'
            ),
            0
        ) AS units_purchased,

        COALESCE(
            SUM(oi.line_revenue) FILTER (
                WHERE o.order_status = 'Completed'
            ),
            0
        ) AS revenue,

        COALESCE(
            SUM(oi.quantity * oi.unit_cost) FILTER (
                WHERE o.order_status = 'Completed'
            ),
            0
        ) AS cost

    FROM customers c

    LEFT JOIN regions r
        ON c.region_id = r.region_id

    LEFT JOIN orders o
        ON c.customer_id = o.customer_id

    LEFT JOIN order_items oi
        ON o.order_id = oi.order_id

    GROUP BY
        c.customer_id,
        c.first_name,
        c.last_name,
        c.segment,
        r.country,
        r.market
)

SELECT
    customer_id,
    first_name,
    last_name,
    segment,
    country,
    market,

    first_order_date,
    last_order_date,

    completed_orders,
    units_purchased,

    ROUND(revenue, 2) AS lifetime_revenue,

    ROUND(cost, 2) AS lifetime_cost,

    ROUND(
        revenue - cost,
        2
    ) AS lifetime_gross_profit,

    ROUND(
        100.0 * (revenue - cost)
        / NULLIF(revenue, 0),
        2
    ) AS gross_margin_pct,

    ROUND(
        revenue
        / NULLIF(completed_orders, 0),
        2
    ) AS average_order_value,

    CASE
        WHEN completed_orders = 0
            THEN 'Never Purchased'

        WHEN completed_orders = 1
            THEN 'One-Time Customer'

        ELSE 'Repeat Customer'
    END AS purchase_status,

    CASE
        WHEN last_order_date IS NULL
            THEN NULL

        ELSE DATE '2025-12-31'
             - last_order_date
    END AS days_since_last_order,

    CASE
        WHEN last_order_date IS NULL
            THEN 'Never Purchased'

        WHEN DATE '2025-12-31'
             - last_order_date <= 90
            THEN 'Active'

        WHEN DATE '2025-12-31'
             - last_order_date <= 180
            THEN 'Watch'

        WHEN DATE '2025-12-31'
             - last_order_date <= 365
            THEN 'At Risk'

        ELSE 'Inactive'
    END AS activity_status

FROM customer_metrics
ORDER BY lifetime_revenue DESC;
