# Customer Analysis Module

## Overview

This module analyses customer value, purchasing behaviour, retention, profitability, revenue concentration, and customer activity using PostgreSQL.

The SQL file `02_customer_analysis.sql` contains a set of business-focused queries designed to help management understand who the most valuable customers are, how frequently customers return, how concentrated revenue is across the customer base, and which customers may require retention attention.

The analysis uses completed orders as realised sales and treats **2025-12-31** as the analytical reference date for recency and inactivity calculations.

---

## Business Objectives

This module answers the following questions:

- Who are the highest-value customers?
- Which customers generate the most revenue?
- How many customers make repeat purchases?
- What is the repeat customer rate?
- How concentrated is revenue across the customer base?
- How many customers are required to generate 80% of total revenue?
- Which customer segments perform best?
- Which countries contain the strongest customer base?
- How frequently do customers place orders?
- Which customers are inactive?
- Which customers are at risk of becoming inactive?
- Which customers have the highest average order value?
- How much revenue comes from new versus repeat customers?
- Which customers generate the most gross profit?
- How much revenue is generated by the top 20% of customers?
- How can customers be grouped into value tiers?
- What customer-level dataset can be used in Power BI?

---

## Key Customer Insights

### Highest-Value Customers

The highest-value customer generated approximately **€18.55K** in completed-order revenue.

The Top 20 customer group is relatively broad rather than being dominated by one single account, which reduces dependency on an individual customer.

Ireland is strongly represented among the highest-value customers, while the Consumer segment dominates the top customer ranking.

### Customer Lifetime Value

Customer Lifetime Value analysis shows meaningful variation across customers in both total revenue and average order value.

Some customers place more frequent orders, while others generate fewer but significantly higher-value purchases.

This distinction helps separate high-frequency customers from high-ticket customers.

### Repeat Purchasing Behaviour

Repeat-customer analysis measures how many customers completed more than one order and provides a direct indication of retention and purchasing loyalty.

The repeat-customer rate can be used as a management KPI to evaluate whether the customer base is primarily transactional or relationship-driven.

### Revenue Concentration

Customer revenue concentration analysis measures the share of total company revenue generated by each individual customer.

This helps identify whether the business depends heavily on a small number of accounts or whether revenue is broadly distributed.

### Pareto 80/20 Analysis

The Pareto analysis ranks customers by revenue and calculates cumulative revenue contribution.

This allows management to identify the number and percentage of customers required to generate approximately 80% of company revenue.

It also enables comparison with the classic 80/20 assumption and shows the actual concentration pattern in this dataset.

### Customer Segment Performance

Customer segments are compared using:

- Customer count
- Completed orders
- Units purchased
- Revenue
- Gross profit
- Gross margin
- Average order value

This identifies which segments contribute the most commercial value and whether higher revenue segments also generate stronger profitability.

### Geographic Customer Performance

Customer performance by country and market highlights geographic differences in:

- Revenue
- Gross profit
- Revenue per customer
- Average order value

This supports geographic customer strategy and market prioritisation.

### Purchase Frequency

Purchase-frequency analysis distinguishes occasional customers from highly engaged repeat buyers.

Customers with high completed-order counts can be prioritised for loyalty, retention, and account-development initiatives.

### Inactive Customers

Customers with no completed purchase during the final 12 months of the analytical period are classified as inactive.

This provides a simple operational list for reactivation campaigns and churn analysis.

### Customer Recency and Churn Risk

Customers are classified into four activity groups:

- Active
- Watch
- At Risk
- Inactive

Customers who have never completed a purchase are identified separately.

This creates a practical churn-risk proxy that can later be used in Power BI or customer-retention reporting.

### High Average Order Value Customers

Customers with the highest average order value are not necessarily the same customers with the highest total revenue.

This distinction helps identify premium customers who purchase less frequently but place larger orders.

### New vs Repeat Customer Revenue

Completed orders are classified as either:

- New Customer
- Repeat Customer

This analysis shows how much revenue is generated from customer acquisition compared with existing-customer retention.

### Customer Profitability

Customers are also ranked by gross profit rather than revenue alone.

This demonstrates that high revenue does not always imply the highest profitability and helps identify the customers creating the greatest economic value.

### Customer Value Tiers

Customers are divided into quartiles using `NTILE(4)`:

- Tier 1 - High Value
- Tier 2 - Upper Mid Value
- Tier 3 - Lower Mid Value
- Tier 4 - Low Value

These tiers provide a practical customer segmentation layer for targeted reporting and commercial decision-making.

---

## SQL Techniques Demonstrated

This module demonstrates practical use of:

- Multi-table `JOIN`s
- `LEFT JOIN`
- Aggregate functions
- `GROUP BY`
- `FILTER`
- `CASE`
- Common Table Expressions (CTEs)
- `ROW_NUMBER()`
- `NTILE()`
- Window functions
- Cumulative revenue
- Revenue-share calculations
- Customer ranking
- Pareto analysis
- Customer recency logic
- Churn-risk segmentation
- Profitability analysis
- Reporting-ready customer datasets

---

## Query Structure

The file contains the following analytical sections:

1. Customer Lifetime Value
2. Top 20 Customers by Revenue
3. Repeat Customers
4. Repeat Customer Rate
5. Customer Revenue Concentration
6. Pareto 80/20 Customer Analysis
7. Customers Required to Generate 80% of Revenue
8. Customer Segment Performance
9. Customer Performance by Country
10. Customer Purchase Frequency
11. Inactive Customers
12. Customer Recency / Churn-Risk Proxy
13. Top Customers by Average Order Value
14. New vs Repeat Customer Revenue
15. Top Customers by Gross Profit
16. Top 20% of Customers vs Revenue Contribution
17. Customer Value Tiers
18. Customer BI Summary Dataset

---

## Power BI Integration

The final query in `02_customer_analysis.sql` produces a reporting-ready customer-level dataset containing:

- Customer ID
- Customer Name
- Segment
- Country
- Market
- First Order Date
- Last Order Date
- Completed Orders
- Units Purchased
- Lifetime Revenue
- Lifetime Cost
- Lifetime Gross Profit
- Gross Margin %
- Average Order Value
- Purchase Status
- Days Since Last Order
- Activity Status

This dataset can later be converted into a PostgreSQL view and connected directly to Power BI.

---

## File Location

```text
projects/sql-business-intelligence/sql/02_customer_analysis.sql
```

## Related Documentation

```text
projects/sql-business-intelligence/documentation/02_CUSTOMER_ANALYSIS.md
```
